# -- Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5832/hale_end_db
spring.datasource.username=hale_end_user
spring.datasource.password=secret
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
